#!/bin/bash

# GFaster Native C++ Qt6 Desktop Application Launcher

if [ -f "/usr/bin/gfaster-gui" ]; then
    exec /usr/bin/gfaster-gui "$@"
elif [ -f "./build/bin/gfaster-gui" ]; then
    exec ./build/bin/gfaster-gui "$@"
elif command -v qml6 &> /dev/null; then
    exec qml6 /usr/share/gfaster/main.qml "$@"
else
    exec qml /usr/share/gfaster/main.qml "$@"
fi
